CREATE TABLE IF NOT EXISTS product_category (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT product_category_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS product (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    price NUMERIC(38, 2) NOT NULL,
    status VARCHAR(255) NOT NULL,
    stock INT NOT NULL,
    version INT NOT NULL,
    category_id BIGINT NOT NULL,
    CONSTRAINT product_pk PRIMARY KEY (id),
    CONSTRAINT product_category_id_fk FOREIGN KEY (category_id) REFERENCES product_category(id)
    );

CREATE TABLE IF NOT EXISTS movement (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    date TIMESTAMP(6) NOT NULL,
    quantity INT NOT NULL,
    type VARCHAR(255) NOT NULL,
    product_id BIGINT NOT NULL,
    CONSTRAINT movement_pk PRIMARY KEY (id),
    CONSTRAINT movement_product_id_fk FOREIGN KEY (product_id) REFERENCES product(id)
);
